<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit6b7d3f7ebd6f6625a6e189a87ef2313f
{
    public static $prefixLengthsPsr4 = array (
        'F' => 
        array (
            'Firebase\\JWT\\' => 13,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Firebase\\JWT\\' => 
        array (
            0 => __DIR__ . '/..' . '/firebase/php-jwt/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit6b7d3f7ebd6f6625a6e189a87ef2313f::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit6b7d3f7ebd6f6625a6e189a87ef2313f::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit6b7d3f7ebd6f6625a6e189a87ef2313f::$classMap;

        }, null, ClassLoader::class);
    }
}
